databases:
  - name: heapoverflow
    user: heapoverflow
    plan: free
    region: oregon

services:
  - type: web
    name: heapoverflow
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render_build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: heapoverflow
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false